### ISSUE TITLE
GCM and other play services dependencies. 

### ISSUE THREAD

**Issue by intmainreturn00** [webim/webim-android-sdk-demo#3]

**Comment by intmainreturn00** [comment]
"You don’t have to be a genius to write fast programs. There’s no magic trick. The only thing required is not building on top of a huge pile of crap that modern toolchain is"

**Comment by webim** [comment]
I see `webimclientsdkandroid:2.2.3`.

Version 2.2.3 was released in 2015. Latest versions don't use this dependencies.

**Comment by webim** [comment]
You should use `'com.webimapp.sdk:webimclientsdkandroid:3.27.3'`.
